# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="noam"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source ~/.aliases

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Don't ask - just update
DISABLE_UPDATE_PROMPT=true

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx brew brew-cask autojump django history-substring-search pip python per-directory-history sudo mvn)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin

# Disable shared history across sessions
# unsetopt SHARE_HISTORY

#virtualenv stuff
# export WORKON_HOME=~/virtualenvs
# mkdir -p $WORKON_HOME
# source /usr/local/bin/virtualenvwrapper.sh
#end virtualenv stuff

# Android stuff
# export ANDROID_HOME=/usr/local/Cellar/android-sdk/24.0.1/
# end Android stuff

# Maven

# moved to /etc/launchd.conf:
# export M2_HOME=/usr/local/apache-maven/apache-maven-3.1.1
# export M2=$M2_HOME/bin

# export PATH=$M2:$JAVA_HOME/bin:$PATH
# end Maven

# Concat several ssh configs...
# printf "###\n### Warning, do not edit this file! Its contents are generated from other config_* files!\n###\n\n" > ~/.ssh/config
# cat ~/.ssh/config_* >> ~/.ssh/config

# cd to project dirs, thanks @yonilevy
autoload bashcompinit
bashcompinit
PROJECTS_HOME=$HOME/code
_cdp_opts() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  IFS=$(echo -en "\n\b") COMPREPLY=( $(compgen -W "`ls $PROJECTS_HOME`" ${cur}) );
}
cdp() {
    cd "$PROJECTS_HOME/$1"
}
complete -F _cdp_opts -o filenames cdp

# list TODOs in current branch (that are not in master), see https://github.com/yonilevy/branchtodo
branchtodo() {
    $WORKON_HOME/branchtodo/bin/python ~/code/branchtodo/branchtodo.py
}

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
export PYTHONPATH=$PYTHONPATH:/Users/noamnelke/Projects/Tapingo

# Detect and activate virtualenvs based on content of .venv file
function check_for_virtual_env {
  if [ -e .venv ]; then
    local virtualenv_name=`cat .venv`
    echo "$reset_color$fg[yellow]Activating virtualenv $fg[green][$virtualenv_name]$reset_color"
    workon $virtualenv_name
  elif [ $VIRTUAL_ENV ]; then
    local virtualenv_name=`basename $VIRTUAL_ENV`
    echo "$reset_color$fg[red]Deactivating virtualenv $fg[green][$virtualenv_name]$reset_color"
    deactivate
  fi
}

# Support for bash
PROMPT_COMMAND='prompt'

# Mirrored support for zsh. See: https://superuser.com/questions/735660/whats-the-zsh-equivalent-of-bashs-prompt-command/735969#735969 
precmd() { eval "$PROMPT_COMMAND" }

function prompt()
{
    if [ "$PWD" != "$MYOLDPWD" ]; then
        MYOLDPWD="$PWD"
        check_for_virtual_env
    fi
}

# Tapingo env
source ~/code/tapingo/noam-config/.tapingo_env
